version: 2

models:
  - name: facttitletable
    description: >
      This is an aggregated table contains full information about the movies, series, and episodes details from the imdb website.
    columns:
          - name: titleid
            description: an alphanumeric unique identifier of the title.
          - name: title
            description: the localized title.
          - name: titleType
            description: the type/format of the title (e.g. movie, short, tvseries, tvepisode, video, etc).
          - name: primaryTitle
            description: the more popular title / the title used by the filmmakers on promotional materials at the point of release.
          - name: originalTitle
            description: original title, in the original language.
          - name: year
            description: represents the release year of a title.
          - name: runtimeMinutes
            description: primary runtime of the title, in minutes
          - name: region
            description: the region for this version of the title
          - name: language
            description: the language of the title
          - name: genres
            description: includes up to three genres associated with the title
          - name: parentTitleId
            description: alphanumeric identifier of the parent TV Series
          - name: seasonNumber
            description: season number the episode belongs to
          - name: episodeNumber
            description: episode number of the tconst in the TV series
          - name: averageRating
            description: weighted average of all the individual user ratings
          - name: numVotes
            description: number of votes the title has received          
          